apiVersion: v1
kind: Service
metadata:
  name: demo-static-site-service
  namespace: default
  labels:
    app: demo-static-site
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-static-site
